name: Test Flux Scheduler
on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        container: ['fluxrm/flux-sched:jammy']
    timeout-minutes: 30

    container:
      image: ${{ matrix.container }}
      options: "--platform=linux/amd64 --user root -it --init"

    name: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies and Parsl
        run: |
          apt-get update && apt-get install -y python3-pip curl
          pip3 install . -r test-requirements.txt

      - name: Verify Parsl Installation
        run: |
          pytest parsl/tests/ -k "not cleannet and not unix_filesystem_permissions_required" --config parsl/tests/configs/local_threads.py --random-order --durations 10

      - name: Test Parsl with Flux
        run: |
          pytest parsl/tests/test_flux.py --config local  --random-order

      - name: Test Parsl with Flux Config
        run: |
          pytest parsl/tests/ -k "not cleannet and not unix_filesystem_permissions_required" --config parsl/tests/configs/flux_local.py --random-order --durations 10


